services:
  db:
    image: postgres:15
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dio_atm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/dio_atm
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: